"""empty message

Revision ID: 431263e56a26
Revises: 
Create Date: 2021-02-04 23:57:33.068310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431263e56a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('exp_date', sa.String(), nullable=True),
    sa.Column('holder', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
