"""empty message

Revision ID: 77a31b748779
Revises: 
Create Date: 2021-02-02 17:00:12.397404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a31b748779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('exp_date', sa.String(), nullable=True),
    sa.Column('holder', sa.String(), nullable=True),
    sa.Column('cvv', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
