"""empty message

Revision ID: ed3defa04f26
Revises: 431263e56a26
Create Date: 2021-02-05 13:39:38.962176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3defa04f26'
down_revision = '431263e56a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'brand')
    # ### end Alembic commands ###
